#ifndef PUTPRAKTYKI2015_GLOBAL_H
#define PUTPRAKTYKI2015_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PUTPRAKTYKI2015_LIBRARY)
#  define PUTPRAKTYKI2015SHARED_EXPORT Q_DECL_EXPORT
#else
#  define PUTPRAKTYKI2015SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PUTPRAKTYKI2015_GLOBAL_H
